---
- name: Tomcat server installed
  hosts: node2
  become: yes
  vars: 
    VER: 9.0.41
  tasks:
   - name: Install OpenJDK 11 
     yum:
       name: java-11-openjdk-devel
       state: latest
   - name: Install Unzip Package
     yum: 
       name: unzip
       state: latest
   - name: Install wget
     yum:
       name: wget
       state: latest
   - name: Update ansible
     yum:
       name: ansible
       state: latest
   - name: Install Firewalld
     yum: 
       name: firewalld
       state: latest
   - name: Start Firewalld service
     service:
       name: firewalld
       state: started
       enabled: yes
   - name: Install Dependences for Firewalld
     shell: sudo ansible-galaxy collection install ansible.posix
   - name:  set Java environment variables
     shell: | 
       cat > /etc/profile.d/java11.sh <<EOF
       export JAVA_HOME=\$(dirname \$(dirname \$(readlink \$(readlink \$(which javac)))))
       export PATH=\$PATH:\$JAVA_HOME/bin
       export CLASSPATH=.:\$JAVA_HOME/jre/lib:\$JAVA_HOME/lib:\$JAVA_HOME/lib/tools.jar
       EOF
   - name: Source the file to start using it without logging out.
     shell: source /etc/profile.d/java11.sh
   - name: Validate Group
     group:
       name: tomcat
       state: present 
     register: group_state
   - name: Create tomcat group   
     shell: sudo groupadd --system tomcat
     when: group_state == "absent"
   - name: Validate User
     user:
       name: tomcat
       state: present 
     register: user_state
   - name: Create user tomcat   
     shell: sudo useradd -d /usr/share/tomcat -r -s /bin/false -g tomcat tomcat
     when: user_state == "absent"
   - name: Install Tomcat 9
     unarchive:
       src: https://archive.apache.org/dist/tomcat/tomcat-9/v{{ VER }}/bin/apache-tomcat-{{ VER }}.tar.gz
       dest: /usr/share/
       remote_src: yes
   - name: Create symlink to extracted tomcat data.
     shell: sudo ln -s /usr/share/apache-tomcat-{{ VER }}/ /usr/share/tomcat
   - name: Set proper directory permissions
     shell: sudo chown -R tomcat:tomcat /usr/share/tomcat
   - name: Set proper directory permissions
     shell: sudo chown -R tomcat:tomcat /usr/share/apache-tomcat-{{ VER }}/
   - name: Create Tomcat 9 Systemd service
     file:
       path: /etc/systemd/system/tomcat.service
       state: touch
   - name: Configure Tomcat 9 Systemd Service
     lineinfile:
       path: /etc/systemd/system/tomcat.service
       line: | 
         [Unit]
         Description=Tomcat Server
         After=syslog.target network.target
         
         [Service]
         Type=forking
         User=tomcat
         Group=tomcat
         Environment=JAVA_HOME=/usr/lib/jvm/jre
         Environment='JAVA_OPTS=-Djava.awt.headless=true'
         Environment=CATALINA_HOME=/usr/share/tomcat
         Environment=CATALINA_BASE=/usr/share/tomcat
         Environment=CATALINA_PID=/usr/share/tomcat/temp/tomcat.pid
         Environment='CATALINA_OPTS=-Xms512M -Xmx1024M'
         ExecStart=/usr/share/tomcat/bin/catalina.sh start
         ExecStop=/usr/share/tomcat/bin/catalina.sh stop
         [Install]
         WantedBy=multi-user.target
       create: yes
   - name: Reload demon 
     shell: sudo systemctl daemon-reload
   - name: Start and enable Tomcat
     service:
       name: tomcat
       state: started
       enabled: yes
   - name: Configure Firewall
     firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
   - name: Reload Firewall
     shell: sudo firewall-cmd --reload
   - name: Configure Tomcat Authentication
     lineinfile:
       path: /usr/share/tomcat/conf/tomcat-users.xml
       regexp: '\<\/tomcat\>'
       line: | 
         <role rolename="admin-gui"/>
         <role rolename="manager-gui"/>
         <role rolename="manager-script"/>
         <role rolename="manager-jmx"/>
         <role rolename="manager-status"/>
         <user username="admin" password="admin"
         roles="admin-gui,manager-gui,manager-script,manager-jmx,manager-status"/>
         </tomcat>
   - name: Configure Tomcat Proxy
     yum:
       name: httpd
       state: latest
   - name: Create VirtualHost for accessing Tomcat Admin web interface
     file:
       path: /etc/httpd/conf.d/tomcat_manager.conf
       state: touch
   - name: Config VirtualHost 
     lineinfile:
       path: /etc/httpd/conf.d/tomcat_manager.conf
       line: | 
         <VirtualHost *:80>
         ServerAdmin root@localhost
         ServerName tomcat.example.com
         DefaultType text/html
         ProxyRequests off
         ProxyPreserveHost On
         ProxyPass / http://localhost:8080/
         ProxyPassReverse / http://localhost:8080/
         </VirtualHost>
   - name: Configure SELinux for Apache to access Tomcat
     shell: |
       sudo setsebool -P httpd_can_network_connect 1
       sudo setsebool -P httpd_can_network_relay 1
       sudo setsebool -P httpd_graceful_shutdown 1
       sudo setsebool -P nis_enabled 1
   - name: Restart httpd service
     service:
       name: httpd
       state: restarted
       enabled: yes
   - name: Enable Tomcat to other hosts
     lineinfile:
       path: /usr/share/tomcat/webapps/manager/META-INF/context.xml
       regexp: 'allow'
       state: present
       line: allow=».*» />
   - name: Enable Tomcat to other hosts
     lineinfile:
       path: /usr/share/tomcat/webapps/host-manager/META-INF/context.xml
       regexp: 'allow'
       state: present
       line: allow=».*» />
   - name: Download Pollo
     shell: |
       cd /usr/share/
       wget https://github.com/jvegaz-javanes/Pollo/archive/main.zip
   - name: Unzip Pollo
     shell: unzip main.zip
   - name: Copy Pollo to Tomcat
     copy:
       src: /usr/share/Pollo-main/polloe.war
       dest: /usr/share/tomcat/webapps
   - name: Restart Tomcat service
     service:
       name: tomcat
       state: restarted
       enabled: yes